<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $report['title'] }} — ABCDips &amp; Treats</title>
    <style>
        @page {
            margin: 25px 30px;
        }
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 11px;
            color: #1C1410;
            background-color: #FFFFFF;
            margin: 0;
            padding: 0;
        }
        .header-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            border-bottom: 2px solid #5C3A22;
            padding-bottom: 10px;
        }
        .brand-title {
            font-size: 20px;
            font-weight: bold;
            color: #5C3A22;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        .report-title {
            font-size: 16px;
            font-weight: bold;
            color: #1C1410;
            margin-top: 4px;
        }
        .report-subtitle {
            font-size: 10px;
            color: #8C7A68;
        }
        .meta-text {
            font-size: 10px;
            color: #8C7A68;
            text-align: right;
        }
        
        /* Summary Stat Cards Grid */
        .summary-box {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        .summary-card {
            background-color: #FBF3E7;
            border: 1px solid #C08E5D;
            padding: 8px 12px;
            border-radius: 6px;
            text-align: center;
        }
        .summary-label {
            font-size: 9px;
            color: #8C7A68;
            text-transform: uppercase;
            font-weight: bold;
        }
        .summary-value {
            font-size: 13px;
            font-weight: bold;
            color: #5C3A22;
            margin-top: 2px;
        }

        /* Data Table */
        .data-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        .data-table th {
            background-color: #5C3A22;
            color: #FFFFFF;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 9px;
            padding: 7px 8px;
            border: 1px solid #5C3A22;
            text-align: left;
        }
        .data-table td {
            padding: 6px 8px;
            border: 1px solid #E5D5C5;
            font-size: 10px;
        }
        .data-table tr:nth-child(even) td {
            background-color: #FDFBF7;
        }

        .footer {
            margin-top: 30px;
            border-top: 1px solid #C08E5D;
            padding-top: 8px;
            font-size: 9px;
            color: #8C7A68;
            text-align: center;
        }
    </style>
</head>
<body>

    <!-- Executive Header -->
    <table class="header-table">
        <tr>
            <td style="vertical-align: top;">
                <div class="brand-title">ABCDIPS &amp; TREATS</div>
                <div class="report-title">{{ $report['title'] }}</div>
                <div class="report-subtitle">{{ $report['subtitle'] }}</div>
            </td>
            <td style="vertical-align: top;" class="meta-text">
                <div><strong>Generated Date:</strong> {{ date('F d, Y h:i A') }}</div>
                <div><strong>Generated By:</strong> Executive Admin System</div>
                <div><strong>Scope:</strong> Live Store Operations</div>
            </td>
        </tr>
    </table>

    <!-- Summary Metrics -->
    @if(!empty($report['summary']))
    <table class="summary-box">
        <tr>
            @foreach($report['summary'] as $label => $val)
            <td class="summary-card">
                <div class="summary-label">{{ $label }}</div>
                <div class="summary-value">{{ $val }}</div>
            </td>
            @endforeach
        </tr>
    </table>
    @endif

    <!-- Main Data Table -->
    <table class="data-table">
        <thead>
            <tr>
                @foreach($report['headings'] as $heading)
                <th>{{ $heading }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse($report['rows'] as $row)
            <tr>
                @foreach($row as $cell)
                <td>{{ $cell }}</td>
                @endforeach
            </tr>
            @empty
            <tr>
                <td colspan="{{ count($report['headings']) }}" style="text-align: center; padding: 15px; color: #8C7A68;">
                    No records found for this report period.
                </td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <!-- Footer -->
    <div class="footer">
        Confidential Internal Business Report • ABCDips &amp; Treats Pastry Management System • Generated on {{ date('Y-m-d H:i:s') }}
    </div>

</body>
</html>
